server:
  port: 8080

spring:
  cloud:
    stream:
      bindings:
        incidences-unprocessed:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.unprocessed
          contentType: application/*+avro

com:
  acme:
    automotive:
      incidencereceiver:
        default-timeout: 5000
