spring:
  cloud:
    stream:
      bindings:
        incidences-unprocessed:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.unprocessed
          contentType: application/*+avro
        incidences-to_assign:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.to_assign
        incidences-assigned:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.assigned
        incidences-to_evolve:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.to_evolve
        incidences-evolved:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.evolved
        incidences-ready:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.ready
        incidences-without_solution:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.without_solution

com:
  acme:
    automotive:
      incidencereceiver:
        # Number of milliseconds for a message sent to enter in a timeout
        default-timeout: 5000
        # Number of seconds a incidence is hold when its status is "IN PROGRESS"
        seconds-to-wait: 120
        #Number of milliseconds the ScheduleIncidencesTask waits to check if must send incidences
        check-period: 1000
