spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27018
      database: local
      #uri: mongodb://localhost:27018/local
  cloud:
    stream:
      function:
        definition: processIncidenceWithoutSolution
      bindings:
        processIncidenceWithoutSolution-in-0:
          destination: queue.incidences.without_solution
          content-type: application/json
          binder: ${com.acme.automotive.currentBinder}
        processIncidenceWithoutSolution-out-0:
          destination: queue.incidences.external
          content-type: application/json
          binder: ${com.acme.automotive.currentBinder}
