spring:
  cloud:
    stream:
      function:
        definition: sendEvolvedIncidenceToIncidenceManager
      bindings:
        sendEvolvedIncidenceToIncidenceManager-in-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.to_evolve
          contentType: application/*+avro
        sendEvolvedIncidenceToIncidenceManager-out-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.evolved
          contentType: application/*+avro

com:
  acme:
    automotive:
      status: IN_PROGRESS,READY,WITHOUT_SOLUTION
      