spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: local
      #uri: mongodb://localhost:27017/local
  cloud:
    stream:
      function:
        definition: receiveSuccessfulIncidence
      bindings:
        receiveSuccessfulIncidence-in-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.ready
          contentType: application/*+avro
