spring:
  cloud:
    stream:
      function:
        definition: sendAssignedIncidenceToIncidenceManager
      bindings:
        sendAssignedIncidenceToIncidenceManager-in-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.to_assign
          content-type: application/json
        sendAssignedIncidenceToIncidenceManager-out-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.assigned
          content-type: application/json

com:
  acme:
    automotive:
      teams: team-aqua,team-magma,team-rocket
      defaultStartStatus: ASSIGNED
