spring:
  cloud:
    stream:
      function:
        definition: sendAssignedIncidenceToIncidenceManager
      bindings:
        sendAssignedIncidenceToIncidenceManager-in-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.to_assign
          contentType: application/*+avro
        sendAssignedIncidenceToIncidenceManager-out-0:
          destination: ${com.acme.automotive.currentExchangeType}.incidences.assigned
          contentType: application/*+avro

com:
  acme:
    automotive:
      teams: team-aqua,team-magma,team-rocket
      defaultStartStatus: ASSIGNED
